/**
 * `renderChildReportText` (ADR-0032 §Rendering, ticket #103): the child report as the text the
 * MODEL reads.
 *
 * Why this is worth its own file. On `surface mode: subagents` there is no `codemode`, so
 * `structuredContent` reaches nobody (ADR-0025 + ADR-0028) and the report's only reader is this
 * block. That makes two properties load-bearing that nothing else checks:
 *
 *  - **a missing report is visibly marked.** Render it as an empty report and the model reads
 *    "the child found nothing", which is a different claim from "the child told us nothing".
 *    The counterfactual test below turns red the moment an implementation swaps one for the other.
 *  - **the 20-finding bound is in-band.** ADR-0032 commits to the number; a report that silently
 *    drops findings past it is indistinguishable from a child that had twenty.
 *
 * SPECIFICATION tests (docs/testing-constraints.md #4/#6): the report is a literal authored from
 * ADR-0032's four fields, in the shape `validateChildReport` accepts, and every expectation is
 * either a literal from that fixture or a number ADR-0032 states. Nothing is asserted against
 * what the renderer happened to produce.
 */
import { describe, expect, test } from "vitest";
import type { ChildReport } from "../../src/runtime/dispatch.ts";
import {
  CHILD_REPORT_HEADER,
  CHILD_REPORT_MAX_EVIDENCE_CHARS,
  CHILD_REPORT_MAX_FILES,
  CHILD_REPORT_MAX_FINDINGS,
  renderChildReportText,
} from "../../src/tools/render.ts";

/**
 * The bound as a LITERAL, never as the exported constant.
 *
 * This is the point of constraint #2 (and of #4's "the expected value must point at an
 * independent source"): a fixture built from `CHILD_REPORT_MAX_FINDINGS` moves with the
 * implementation, so raising the bound to 100 leaves every bound test green and the ADR's
 * commitment unobserved. ADR-0032 §Rendering states the number, so the tests hold the number and
 * the implementation is measured against it.
 */
const ADR_MAX_FINDINGS = 20;
/** The file list's cap is this renderer's own choice, on ADR-0032's rule rather than its number. */
const RENDERED_MAX_FILES = 20;
/**
 * The evidence cap, sized so the row — connector, index padding, `evidence: `, the truncated text
 * AND the notice that says it was truncated — still fits `MAX_LINE_CHARS` (200). Raise it and the
 * notice is cut off by the same row it was meant to annotate.
 */
const RENDERED_MAX_EVIDENCE_CHARS = 150;

/**
 * A literal compliant report, in the four-field shape ADR-0032 defines.
 *
 * The three declared fields are the child's; `usage` is HOST-observed and stamped at settle from
 * the child's own `message_end` usage blocks (`ChildReportPayload`), so this fixture carries a
 * measurement the host made rather than one a child could have made up. The two findings are
 * taken from this repo's own concurrency work, which is where a report of this shape comes from.
 */
const COMPLIANT_REPORT: ChildReport = {
  summary: "The concurrency gate precedes agent discovery, so nothing is spawned.",
  findings: [
    {
      what: "the slot acquire happens before discoverAgent",
      evidence:
        "dispatchConcurrencyLimitReached() returns from the acquire branch, above discovery",
    },
    {
      what: "the background refusal reuses the foreground wording",
      evidence: "backgroundDispatchConcurrencyLimitReached() spreads the foreground error object",
    },
  ],
  files_touched: ["src/runtime/dispatch.ts", "tests/unit/ptc-subagent.test.ts"],
  usage: { input: 1200, output: 340, cost: 0.0123, turns: 4 },
};

/** A report with no findings and no files: empty containers, not a missing report. */
const EMPTY_REPORT: ChildReport = {
  summary: "Nothing in the working tree references the removed export.",
  findings: [],
  files_touched: [],
  usage: { input: 800, output: 0, cost: 0, turns: 1 },
};

/**
 * The bound fixtures. Generated by repeating ONE literal finding rather than hand-writing 23,
 * so the only thing varying across the list is its length — which is the property under test.
 */
function findingsOf(count: number): ChildReport["findings"] {
  return Array.from({ length: count }, (_unused, index) => ({
    what: `claim number ${index}`,
    evidence: `support for claim ${index}`,
  }));
}

function filesOf(count: number): string[] {
  return Array.from({ length: count }, (_unused, index) => `src/generated/file-${index}.ts`);
}

/** The index of `needle` in `haystack`, failing loudly rather than returning -1. */
function indexOf(haystack: string, needle: string): number {
  const at = haystack.indexOf(needle);
  if (at < 0) throw new Error("rendered block does not contain " + JSON.stringify(needle));
  return at;
}

describe("renderChildReportText — the report a model reads", () => {
  test("summary, findings, files and usage render in that fixed order", () => {
    // The order IS the contract (ADR-0032 §Rendering: conclusion first, then the supporting
    // facts). A renderer that emitted findings above the summary would still contain every word
    // below, so the assertion has to be positional or it pins nothing.
    const block = renderChildReportText(COMPLIANT_REPORT, "prompt-json");
    const summary = indexOf(block, "summary");
    const findings = indexOf(block, "findings");
    const files = indexOf(block, "files");
    const usage = indexOf(block, "usage");
    expect(summary).toBeLessThan(findings);
    expect(findings).toBeLessThan(files);
    expect(files).toBeLessThan(usage);
  });

  test("every finding renders with its own evidence, not merged or dropped", () => {
    const block = renderChildReportText(COMPLIANT_REPORT, "prompt-json");
    for (const finding of COMPLIANT_REPORT.findings) {
      expect(block, "the claim the child made is in the block").toContain(finding.what);
      expect(block, "and the evidence it rested on").toContain(finding.evidence);
    }
    // Numbered, so a renderer that printed every finding on one line without indices would
    // still pass the `toContain` above; the two claims are two rows.
    expect(block, "findings are addressed individually").toContain(
      "[0]  " + COMPLIANT_REPORT.findings[0]?.what,
    );
    expect(block).toContain("[1]  " + COMPLIANT_REPORT.findings[1]?.what);
    expect(block, "the count is the child's, stated in-band").toContain("Array(2)");
  });

  test("files and usage render the host's numbers", () => {
    const block = renderChildReportText(COMPLIANT_REPORT, "prompt-json");
    for (const file of COMPLIANT_REPORT.files_touched) {
      expect(block, "a path the child touched is in the block").toContain(file);
    }
    expect(block, "and both are addressed by index").toContain("Array(2)");
    // `usage` is host-observed (ChildReportPayload), so these are measurements, not claims:
    // the assertion is that the rendered row states exactly the numbers the host stamped.
    expect(block).toContain("in 1200");
    expect(block).toContain("out 340");
    expect(block).toContain("cost 0.0123");
    expect(block, "turns are pluralised off the measured count").toContain("4 turns");
  });

  test("the header names the channel the report arrived over", () => {
    // `reportChannel` is TOTAL on `DispatchResult`, so the channel is always nameable — and
    // naming it is the difference between "the child reported this" and "something parsed this".
    expect(renderChildReportText(COMPLIANT_REPORT, "prompt-json")).toContain(
      `${CHILD_REPORT_HEADER} (channel: prompt-json)`,
    );
    expect(renderChildReportText(COMPLIANT_REPORT, "tool")).toContain(
      `${CHILD_REPORT_HEADER} (channel: tool)`,
    );
  });

  test("an empty report renders as an empty report, with the counts saying so", () => {
    // The contrast case for the next one: a child that reported NOTHING found still renders a
    // full block, and `[]` is how the value tree renders an empty container.
    const block = renderChildReportText(EMPTY_REPORT, "prompt-json");
    expect(block).toContain("summary");
    expect(block, "zero findings is stated, not left blank").toContain("findings");
    expect(block).toContain("files");
    expect(block).toContain("usage");
    expect(block, "and the empty collections are marked `[]`").toContain("[]");
    expect(block, "usage is still reported even with nothing found").toContain("1 turn");
  });
});

describe("renderChildReportText — a report that never arrived", () => {
  test("no report is marked in the text rather than rendered as an empty report", () => {
    // COUNTERFACTUAL (constraint 5). Make `renderChildReportText` treat `undefined` as
    // EMPTY_REPORT and this test goes red on all four assertions below, because an empty report
    // is a full block of sections and none of them says the report is missing. There is no
    // version of "render it empty" that satisfies the intent of this file.
    const block = renderChildReportText(undefined, "none");
    expect(block, "the block is still emitted, so the gap is visible").toContain(
      CHILD_REPORT_HEADER,
    );
    expect(block, "and it names the channel that produced nothing").toContain("channel: none");
    expect(block, "and it says the report is absent").toContain("no child report was returned");
    // The precise shape of the failure this guards: an empty report's sections are the words
    // below. A reader cannot tell "found nothing" from "said nothing" without them.
    expect(block, "no summary row, which is what 'found nothing' would print").not.toContain(
      "summary",
    );
    expect(block, "no findings row").not.toContain("findings");
    expect(block, "no files row").not.toContain("files");
    expect(block, "no usage row").not.toContain("usage");
  });

  test("a channel that claims a report but carries none is marked too", () => {
    // The defensive branch: `reportChannel` names the channel the extraction ATTEMPTED, so a
    // caller that pairs it with no report is stating something the block must not paper over.
    const block = renderChildReportText(undefined, "prompt-json");
    expect(block).toContain("channel: prompt-json");
    expect(block, "and the gap is still marked, not quietly filled").toContain(
      "no report reached the host",
    );
    expect(block).not.toContain("summary");
  });
});

describe("renderChildReportText — the bounds, stated in-band", () => {
  test("the exported bounds are the ones this file holds them to", () => {
    // The measurements below would be re-derived from these constants in a moment; this is the
    // one place they are compared, so a bound moved without a decision fails here rather than
    // silently rewriting the fixtures above.
    expect(CHILD_REPORT_MAX_FINDINGS, "ADR-0032 §Rendering commits to 20 findings").toBe(
      ADR_MAX_FINDINGS,
    );
    expect(CHILD_REPORT_MAX_FILES).toBe(RENDERED_MAX_FILES);
    expect(CHILD_REPORT_MAX_EVIDENCE_CHARS, "sized against the row width, not chosen freely").toBe(
      RENDERED_MAX_EVIDENCE_CHARS,
    );
  });

  test("exactly 20 findings render in full, with no withheld tail", () => {
    // The boundary itself, from both sides: at the bound nothing is withheld, so a tail row
    // here would be a count of zero claiming something was cut.
    const report: ChildReport = {
      ...COMPLIANT_REPORT,
      findings: findingsOf(ADR_MAX_FINDINGS),
    };
    const block = renderChildReportText(report, "prompt-json");
    expect(block).toContain("claim number " + (ADR_MAX_FINDINGS - 1));
    expect(block).not.toContain("withheld");
    expect(block, "the count is the child's, not the bound's").toContain(
      `Array(${ADR_MAX_FINDINGS})`,
    );
  });

  test("past 20 findings the first 20 render and the withheld count is stated", () => {
    // ADR-0032 §Rendering: "bounded at 20 findings with the withheld count stated in-band".
    const total = ADR_MAX_FINDINGS + 3;
    const report: ChildReport = { ...COMPLIANT_REPORT, findings: findingsOf(total) };
    const block = renderChildReportText(report, "prompt-json");

    expect(block, "the first finding renders").toContain("claim number 0");
    expect(
      block,
      "and so does the twentieth — the bound is inclusive, not nineteen-and-a-tail",
    ).toContain(`claim number ${ADR_MAX_FINDINGS - 1}`);
    expect(block, "the twenty-first is NOT rendered").not.toContain(
      `claim number ${ADR_MAX_FINDINGS}`,
    );
    // The count, by name: the value tree's convention is `…+N more`, and naming the noun is what
    // makes it usable — `…+3 more` alone could be findings, files or lines.
    expect(block, "the withheld COUNT is stated, not just an ellipsis").toContain(
      "…+3 more findings withheld",
    );
    expect(block, "and the bound itself is named, so the reader knows it is a bound").toContain(
      `at most ${ADR_MAX_FINDINGS}`,
    );
    // The child's own count survives, so a reader learns the report was longer than the bound.
    expect(block).toContain(`Array(${total})`);
  });

  test("files_touched is bounded on the same rule and says so", () => {
    const total = RENDERED_MAX_FILES + 2;
    const report: ChildReport = {
      ...COMPLIANT_REPORT,
      files_touched: filesOf(total),
    };
    const block = renderChildReportText(report, "prompt-json");
    expect(block).toContain("src/generated/file-0.ts");
    expect(block).not.toContain(`src/generated/file-${RENDERED_MAX_FILES}.ts`);
    expect(block, "and the withheld count is stated").toContain(
      `…+2 more files withheld (a report renders at most ${RENDERED_MAX_FILES})`,
    );
  });

  test("evidence long enough to be cut says that it was cut", () => {
    // Silently shortening a piece of evidence is how a model ends up quoting half a sentence as
    // the whole claim, so the cap announces itself on the row it applies to.
    const long = "x".repeat(RENDERED_MAX_EVIDENCE_CHARS + 40);
    const report: ChildReport = {
      ...COMPLIANT_REPORT,
      findings: [{ what: "a claim whose evidence is long", evidence: long }],
    };
    const block = renderChildReportText(report, "prompt-json");
    expect(block).toContain(`evidence: ${"x".repeat(RENDERED_MAX_EVIDENCE_CHARS)}`);
    expect(block, "the cut is stated in-band, on the row it applies to").toContain(
      `truncated at ${RENDERED_MAX_EVIDENCE_CHARS} chars`,
    );
    expect(block, "and no untruncated evidence was rendered").not.toContain(long);
  });

  test("evidence inside the cap is left whole and says nothing about truncation", () => {
    // The other side of that boundary. A renderer that appended the notice unconditionally
    // would claim a cut that did not happen, which is the same defect in the other direction.
    const block = renderChildReportText(COMPLIANT_REPORT, "prompt-json");
    expect(block).toContain(COMPLIANT_REPORT.findings[0]?.evidence ?? "");
    expect(block).not.toContain("truncated at");
  });
});
